cookie:
  expiry_days: 30
  key: abcdef123456
  name: ai_study_buddy_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 2
      name: Admin User
      password: $2b$12$HE.1mPTj2/YcGQPl/CZtmOto0q0ZhQie2PvfsNP3K/eCpbOFFrM.q
    demo1:
      email: example@gmail.com
      failed_login_attempts: 0
      first_name: demo
      last_name: demo
      logged_in: true
      password: $2b$12$m8UU175pIP3DeYSpGscuJeFvFt3VT0ZG4soMd7B51eSknRvDn7rx6
      password_hint: car
      progress:
        by_subject:
          Computer Science: 2
        total_questions: 2
        total_quizzes: 0
      roles: null
preauthorized:
  emails: []
user_progress:
  demo1:
    by_subject:
      Computer Science: 1
    total_questions: 1
    total_quizzes: 0
